### ISSUE TITLE
[dash]: recent applications: new clicked app is put in 9th position if more than 9 apps are listed

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.8#31]

**Comment by eikehein** [comment]
Can you show us a video or a screenshots or so? I don't really understand this well without a visual, and I need to sort out if it's a UI code problem or KActivities backend :)

**Comment by star-buck** [comment]
Simply start 10 different apps from dash to see: the last app is not put in
first position under recent app, but 9th.

**Comment by ivan-cukic** [comment]
(copying from https://github.com/blue-systems/plasma-5.5/issues/26)

The issue of the wrongly sorted items in the recent applications should be resolved with the KF28 release (current master).

Mind that this issue was with all applications that are used for the first time, not only for newly installed applications (KAStats library has no idea what applications are to be influenced by whether something is or is not newly installed).

**Comment by star-buck** [comment]
happens again, not in 9th position, but randomly (mostly 2nd position):
https://www.dropbox.com/s/x69173og2if2ou4/dash-recent.mkv?dl=0

**Comment by ivan-cukic** [comment]
Does it move to the right position at some point?
Does it move to the right position if you restart plasma?
And does it happen only when you start multiple applications in short period of time, or it does not matter how much time passed between consecutive starts?

**Comment by star-buck** [comment]
@eikehein : still not fixed with plasma 5.12.2:
before:
![screenshot_20180310_132910](https://user-images.githubusercontent.com/840070/37242292-24a3626a-2467-11e8-98c6-c288d65d7b08.png)


after opening writer, its only second position:
![screenshot_20180310_132927](https://user-images.githubusercontent.com/840070/37242295-296ae16a-2467-11e8-94f0-ec12dcf578bb.png)

**Comment by star-buck** [comment]
after starting dolphin and ksnakeduel:
![screenshot_20180310_133526](https://user-images.githubusercontent.com/840070/37242329-fbd109d6-2467-11e8-9cb4-5396571160bc.png)

**Comment by star-buck** [comment]
and still not fixed with plasma 5.13 with latest kde neon pinebook img...

Test by switch to dash and open gwenview, then open okular, gwenview is still in first position...
@eikehein : can you give this priority? it looks bad and beats the purpose of having this default as first option when it is clearly still not working as advertised.

**Comment by star-buck** [comment]
looks like icons get somehow inserted sorted A-Z.
But then even that is not always consistent, like Firefox Browser is at spot 1, while Ark is sorted second spot (but logically before all others then following, so i guess its internhal screwed to not recognize the first spot).

**Comment by eikehein** [comment]
It's a KActivities bug, so the reason it fell by the wayside is that the responsible and knowledgable employee went away. I'll see if I can reproduce and figure something out, but it might involve some learning overhead to get familiar with the KA stuff.

**Comment by star-buck** [comment]
that would be great.
(the responsible and knowledgable employee didnt seem to fix it while he was still assigned).

**Comment by eikehein** [comment]
Patch: https://phabricator.kde.org/D13273

Turned out to be in the Kicker backend, after all - and super trivial ...

**Comment by eikehein** [comment]
Fix is merged into the 5.12/5.13/master branches.

**Comment by star-buck** [comment]
@eikehein : 5.13.2 here and still not working? tested on netrunner rolling based on manjaro/arch.
Is it supposed to be officially bugfixed with 5.13.x?

**Comment by eikehein** [comment]
The fix is in 5.13.1+. It works for me here. Maybe there's a second bug ...

In the Dashboard preferences, do you have "Sort alphabetically" enabled?

**Comment by eikehein** [comment]
^ I think it's that - this setting is also applied to the Recent Apps model *facepalm*. So there were two "sort alphabetically" bugs. I didn't notice the second one because that setting is default-off. I'll fix it.

**Comment by eikehein** [comment]
(Ah, it's also a recent regression from expanding alpha sorting to the top-level menu.)

**Comment by eikehein** [comment]
I tracked this down to a bug in KActivitiesStats after all. I don't have time to fix it.

I filed a bug so Ivan can fix it: https://bugs.kde.org/show_bug.cgi?id=396102

And I wrote this workaround patch I hope to merge in the meantime, if the rest of the team allows me to do it: https://phabricator.kde.org/D13856

Alternatively, it might provoke someone else into fixing the underlying KActivitiesStats bug.

**Comment by eikehein** [comment]
The underlying bug is now fixed in KActivitiesStats by David and will be released with KF5 5.48.

My workaround patch also contained a crashfix aside from the workaround, so I kept just the crashfix and merged that.
